[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x', 'openssl']

[phases.install]
cmds = [
  'npm ci',
  'cd backend && npm ci',
  'cd frontend && npm ci'
]

[phases.build]
cmds = [
  'npx prisma generate --schema=./prisma/schema.prisma',
  'cd frontend && npm run build'
]

[start]
cmd = 'npm run start:production'